### ISSUE TITLE
Pass headers

### ISSUE THREAD

**Issue by wuilmerj24** [valor-software/nativescript-plugins#10]
Hi, how to pass header websocket plugin?

**Comment by wuilmerj24** [comment]
?

**Comment by edusperoni** [comment]
Although not officially supported in the web spec, we expose an extra options object you can use:

https://github.com/valor-software/nativescript-plugins/blob/f6e7ba3d68802363ea5d507167e42d16a64eb52e/packages/nativescript-websockets/websocket.ts#L82

so you can just:

```
new WebSocket(url, protocol, {headers: { 'x-my-header': 'value' } } );
```
